# fly.toml app configuration file generated for moviex on 2023-10-11T15:18:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moviex"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[[services]]
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
