// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/samuelagm/moviex/ent/character"
	"github.com/samuelagm/moviex/ent/comment"
	"github.com/samuelagm/moviex/ent/movie"
	"github.com/samuelagm/moviex/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	characterFields := schema.Character{}.Fields()
	_ = characterFields
	// characterDescName is the schema descriptor for name field.
	characterDescName := characterFields[0].Descriptor()
	// character.DefaultName holds the default value on creation for the name field.
	character.DefaultName = characterDescName.Default.(string)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescText is the schema descriptor for text field.
	commentDescText := commentFields[1].Descriptor()
	// comment.TextValidator is a validator for the "text" field. It is called by the builders before save.
	comment.TextValidator = commentDescText.Validators[0].(func(string) error)
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescTitle is the schema descriptor for title field.
	movieDescTitle := movieFields[0].Descriptor()
	// movie.DefaultTitle holds the default value on creation for the title field.
	movie.DefaultTitle = movieDescTitle.Default.(string)
	// movieDescEpisodeID is the schema descriptor for episode_id field.
	movieDescEpisodeID := movieFields[1].Descriptor()
	// movie.EpisodeIDValidator is a validator for the "episode_id" field. It is called by the builders before save.
	movie.EpisodeIDValidator = movieDescEpisodeID.Validators[0].(func(int) error)
	// movieDescOpeningCrawl is the schema descriptor for opening_crawl field.
	movieDescOpeningCrawl := movieFields[2].Descriptor()
	// movie.DefaultOpeningCrawl holds the default value on creation for the opening_crawl field.
	movie.DefaultOpeningCrawl = movieDescOpeningCrawl.Default.(string)
}
