// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Character is the predicate function for character builders.
type Character func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)
